version: '3.8'

services:
  postgresql:
    image: postgres:latest
    container_name: ${APP_NAME}-db
    environment:
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - ${POSTGRESQL_PORT}:5432
    volumes:
      - postgresql-db:/var/lib/postgresql/data
    networks:
      - postgresql-network
    restart: always

volumes:
  postgresql-db:

networks:
  postgresql-network:
    driver: bridge
